---
- name: install apache
  yum: name={{ item }} state=latest
  with_items:
    - httpd
    - openssl
    - mod_ssl
- name: deploy vhosts.conf file
  template: src=vhosts.conf dest=/etc/httpd/conf.d/vhosts.conf
  notify: restart apache
- name: disable sendfile option
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    regexp='EnableSendfile on'
    line='EnableSendfile off'
  notify: restart apache
- name: start apache and enabled
  service: name=httpd state=started enabled=yes
